export MINIO_ROOT_USER="adm1n_usr"
export MINIO_ROOT_PASSWORD="K7MDENG_pass"
export POSTGRES_USER="adm1n"
export POSTGRES_DB="postgres"
export POSTGRES_PASSWORD="_1_p0sTgr3s!>DB"
export REDIS_PASSWORD="MDNcVb924a"